services:
  aihelms:
    volumes:
      - ./apps:/app
    environment:
      DEBUG: "true"
    command: ["uvicorn", "main:app", "--reload", "--host", "0.0.0.0", "--port", "${AIHELMS_PORT:-8000}"]

  db:
    ports:
      - "5432:5432"

  redis:
    ports:
      - "6379:6379"
