export type { User, CreateUserParams, UpdateUserParams, UserListResult } from './types/user'
export type { CurrentUser, LoginParams, TokenData, ChangePasswordParams } from './types/auth'
export type { Department, DeptTreeNode, DeptManager, CreateDepartmentParams, UpdateDepartmentParams, DeptMember } from './types/department'
export type { Project, CreateProjectParams, UpdateProjectParams, ProjectMember, ProjectListResult } from './types/project'
export type { Role, Permission, CreateRoleParams, UpdateRoleParams } from './types/role'
export type { AiKey, CreateAiKeyParams, UpdateAiKeyParams, AiKeyListResult, MyKeysResult, IdentityUserItem, IdentityDepartmentItem, IdentityProjectItem, IdentityListResult, AiKeyModelLimit, SetModelLimitItem } from './types/ai-key'
export type { Provider, CreateProviderParams, UpdateProviderParams, ProviderListResult } from './types/provider'
export type { Credential, CreateCredentialParams, UpdateCredentialParams, CredentialListResult, ProviderFieldMetadata, ProviderFieldsInfo } from './types/credential'
export type { ModelInfo, Deployment, CreateModelParams, UpdateModelParams, CreateDeploymentParams, UpdateDeploymentParams, ModelListResult, ActiveModel, AccessGroup, CreateAccessGroupParams, UpdateAccessGroupParams, RouterSettings, UpdateRouterSettingsParams } from './types/model'
export type { ApiResponse } from './api/request'

export { request } from './api/request'
export { login, getMe, changePassword } from './api/auth'
export { getUsers, getUserById, createUser, updateUser, deleteUser, resetUserPassword, updateUserRoles, updateUserDepartments, updateUserProjects } from './api/user'
export { getDepartmentTree, getDepartmentById, createDepartment, updateDepartment, deleteDepartment, getDepartmentMembers, addDepartmentMember, removeDepartmentMember, updateDepartmentManagers } from './api/department'
export { getProjects, getProjectById, createProject, updateProject, deleteProject, getProjectMembers, addProjectMember, removeProjectMember } from './api/project'
export { getRoles, createRole, updateRole, deleteRole, updateRolePermissions, getPermissions } from './api/role'
export { getAiKeys, getAiKeyById, createAiKey, updateAiKey, toggleAiKey, deleteAiKey, getMyKeys, getIdentityList, getModelLimits, setModelLimits, deleteModelLimit } from './api/ai-key'
export { getProviders, getProviderById, createProvider, updateProvider, deleteProvider } from './api/provider'
export { getCredentials, getCredentialById, createCredential, updateCredential, deleteCredential, getProviderFields } from './api/credential'
export { getModels, getModelById, getActiveModels, createModel, updateModel, deleteModel, createDeployment, updateDeployment, deleteDeployment, getAccessGroups, createAccessGroup, updateAccessGroup, deleteAccessGroup, getRouterSettings, updateRouterSettings } from './api/model'
export { useAuth } from './composables/useAuth'
export { usePermission } from './composables/usePermission'
