export type { User, CreateUserParams, UpdateUserParams, UserListResult } from './types/user'
export type { CurrentUser, LoginParams, TokenData, ChangePasswordParams } from './types/auth'
export type { Department, DeptTreeNode, DeptManager, CreateDepartmentParams, UpdateDepartmentParams, DeptMember } from './types/department'
export type { Project, CreateProjectParams, UpdateProjectParams, ProjectMember, ProjectListResult } from './types/project'
export type { Role, Permission, CreateRoleParams, UpdateRoleParams } from './types/role'
export type { ApiResponse } from './api/request'

export { request } from './api/request'
export { login, getMe, changePassword } from './api/auth'
export { getUsers, getUserById, createUser, updateUser, deleteUser, resetUserPassword, updateUserRoles, updateUserDepartments, updateUserProjects } from './api/user'
export { getDepartmentTree, getDepartmentById, createDepartment, updateDepartment, deleteDepartment, getDepartmentMembers, addDepartmentMember, removeDepartmentMember, updateDepartmentManagers } from './api/department'
export { getProjects, getProjectById, createProject, updateProject, deleteProject, getProjectMembers, addProjectMember, removeProjectMember } from './api/project'
export { getRoles, createRole, updateRole, deleteRole, updateRolePermissions, getPermissions } from './api/role'
export { useAuth } from './composables/useAuth'
export { usePermission } from './composables/usePermission'
