[supervisord]
nodaemon=true
user=root
logfile=/logs/supervisord.log
logfile_maxbytes=10MB
logfile_backups=3
pidfile=/tmp/supervisord.pid

[unix_http_server]
file=/tmp/supervisor.sock

[supervisorctl]
serverurl=unix:///tmp/supervisor.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[program:gunicorn]
command=gunicorn main:app -c gunicorn_conf.py
directory=/app/apps
autostart=true
autorestart=true
startsecs=5
startretries=3
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:celery-worker]
command=celery -A celery_app worker --loglevel=%(ENV_CELERY_LOGLEVEL)s --concurrency=%(ENV_CELERY_WORKER_CONCURRENCY)s --prefetch-multiplier=%(ENV_CELERY_PREFETCH_MULTIPLIER)s
directory=/app/apps
autostart=true
autorestart=true
startsecs=5
startretries=3
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:celery-beat]
command=celery -A celery_app beat --loglevel=%(ENV_CELERY_LOGLEVEL)s
directory=/app/apps
autostart=true
autorestart=true
startsecs=5
startretries=3
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
